apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpusprint-simulated-fleet
  namespace: gpusprint-system
  labels:
    app: gpusprint-simulated-fleet
spec:
  replicas: 100
  selector:
    matchLabels:
      app: gpusprint-simulated-fleet
  template:
    metadata:
      labels:
        app: gpusprint-simulated-fleet
    spec:
      serviceAccountName: gpusprint
      containers:
      - name: gpusprint
        image: gpusprint:local
        imagePullPolicy: Never    # Use local image from minikube
        env:
        # We use the Pod Name as the Node Name so that each of the 100 replicas
        # acts like a unique Kubernetes node in the telemetry output!
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DEVELOPMENT_MODE
          value: "true"
        - name: LOG_LEVEL
          value: "info"
        - name: SAMPLE_INTERVAL
          value: "15s"
        - name: PUBSUB_ENABLED
          value: "false"
        - name: OTLP_ENABLED
          value: "true"
        - name: OTLP_ENDPOINT
          value: "otel-collector.gpusprint-system.svc.cluster.local:4317"
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi
