image:
  repository: gpusprint
  tag: "local"
  pullPolicy: Never

config:
  developmentMode: "true"
  logLevel: "info"
  sampleInterval: "30s"
  numGPUs: "12"

  prometheus:
    enabled: "true"
  pubsub:
    enabled: "false"
  otlp:
    enabled: "false"
    # enabled: "true"
    # endpoint: "otel-collector.gpusprint-system.svc.cluster.local:4317"

resources:
  requests:
    cpu: 10m
    memory: 24Mi
  limits:
    cpu: 50m
    memory: 48Mi
