apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  namespace: gpusprint-system
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    exporters:
      debug:
        verbosity: detailed
      googlecloud:
        project: gpusprint-dev
    service:
      pipelines:
        metrics:
          receivers: [otlp]
          exporters: [debug, googlecloud]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: gpusprint-system
spec:
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:0.110.0
        command: ["/otelcol-contrib", "--config=/etc/otelcol/config.yaml"]
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        volumeMounts:
        - name: config-volume
          mountPath: /etc/otelcol
        - name: google-cloud-key
          mountPath: /var/secrets/google
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: otel-collector-conf
      - name: google-cloud-key
        secret:
          secretName: google-cloud-key
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: gpusprint-system
spec:
  ports:
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
  - name: otlp-http
    port: 4318
    targetPort: 4318
  selector:
    app: otel-collector
